version: '3.9'

services:
  database:
    image: mysql
    platform: linux/x86_64
    container_name: hiartes
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'hiartes'
      MYSQL_DATABASE: 'hiartes'
    ports:
      - '3307:3306'
